export const USERS = {
    REQUEST: "GET_USER_REQUEST",
    SUCCESS: "GET_USER_SUCCESS",
    FAIL: "GET_USER_FAIL",
}


export const ADD_USERS = {
    REQUEST: "ADD_USER_REQUEST",
    SUCCESS: "ADD_USER_SUCCESS",
    FAIL: "ADD_USER_FAIL",
}

export const UPDATE_USERS = {
    REQUEST: "UPDATE_USER_REQUEST",
    SUCCESS: "UPDATE_USER_SUCCESS",
    FAIL: "UPDATE_USER_FAIL",
}

export const DELETE_USERS = {
    REQUEST: "DELETE_USER_REQUEST",
    SUCCESS: "DELETE_USER_SUCCESS",
    FAIL: "DELETE_USER_FAIL",
}